// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func initApp() (*app, error) {
	router := initRouter()
	server := initServer(router)
	mainApp := &app{
		srv: server,
	}
	return mainApp, nil
}
